export const ActionTypes = {
  /* login */

  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",

  /* logout */

  LOGOUT: "LOGOUT",

  /* sign up */
  
  SIGN_UP_REQUEST: "SIGN_UP_REQUEST",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE",  

  //usuaries Reducer

  GET_USUARIES: "GET_USUARIES",
  REMOVE_USUARIES: "REMOVE_USUARIES",
}
